/**
 * ZIABRIDGE Shared Language Dataset
 * Full list of languages supported by Google Translate, each shown in its
 * OWN native script/name (not translated). The "Select Language" title
 * stays in English always - see lang-dropdown-title in the HTML.
 *
 * Used by: js/script.js (language dropdown), all pages.
 * This only provides data + a render helper - it does not touch the
 * Google Translate engine itself.
 */

const ZIABRIDGE_LANGUAGES = [
  { code: "en", native: "English" },
  { code: "af", native: "Afrikaans" },
  { code: "sq", native: "Shqip" },
  { code: "am", native: "አማርኛ" },
  { code: "ar", native: "العربية" },
  { code: "hy", native: "Հայերեն" },
  { code: "as", native: "অসমীয়া" },
  { code: "ay", native: "Aymar aru" },
  { code: "az", native: "Azərbaycan dili" },
  { code: "bm", native: "Bamanankan" },
  { code: "eu", native: "Euskara" },
  { code: "be", native: "Беларуская" },
  { code: "bn", native: "বাংলা" },
  { code: "bho", native: "भोजपुरी" },
  { code: "bs", native: "Bosanski" },
  { code: "bg", native: "Български" },
  { code: "ca", native: "Català" },
  { code: "ceb", native: "Cebuano" },
  { code: "ny", native: "Chichewa" },
  { code: "zh-CN", native: "中文（简体）" },
  { code: "zh-TW", native: "中文（繁體）" },
  { code: "co", native: "Corsu" },
  { code: "hr", native: "Hrvatski" },
  { code: "cs", native: "Čeština" },
  { code: "da", native: "Dansk" },
  { code: "dv", native: "ދިވެހި" },
  { code: "doi", native: "डोगरी" },
  { code: "nl", native: "Nederlands" },
  { code: "eo", native: "Esperanto" },
  { code: "et", native: "Eesti" },
  { code: "ee", native: "Eʋegbe" },
  { code: "tl", native: "Filipino" },
  { code: "fi", native: "Suomi" },
  { code: "fr", native: "Français" },
  { code: "fy", native: "Frysk" },
  { code: "gl", native: "Galego" },
  { code: "ka", native: "ქართული" },
  { code: "de", native: "Deutsch" },
  { code: "el", native: "Ελληνικά" },
  { code: "gn", native: "Guarani" },
  { code: "gu", native: "ગુજરાતી" },
  { code: "ht", native: "Kreyòl Ayisyen" },
  { code: "ha", native: "Hausa" },
  { code: "haw", native: "ʻŌlelo Hawaiʻi" },
  { code: "iw", native: "עברית" },
  { code: "hi", native: "हिन्दी" },
  { code: "hmn", native: "Hmoob" },
  { code: "hu", native: "Magyar" },
  { code: "is", native: "Íslenska" },
  { code: "ig", native: "Igbo" },
  { code: "ilo", native: "Ilokano" },
  { code: "id", native: "Bahasa Indonesia" },
  { code: "ga", native: "Gaeilge" },
  { code: "it", native: "Italiano" },
  { code: "ja", native: "日本語" },
  { code: "jw", native: "Basa Jawa" },
  { code: "kn", native: "ಕನ್ನಡ" },
  { code: "kk", native: "Қазақ тілі" },
  { code: "km", native: "ខ្មែរ" },
  { code: "rw", native: "Kinyarwanda" },
  { code: "gom", native: "कोंकणी" },
  { code: "ko", native: "한국어" },
  { code: "kri", native: "Krio" },
  { code: "ku", native: "Kurdî" },
  { code: "ckb", native: "کوردیی ناوەندی" },
  { code: "ky", native: "Кыргызча" },
  { code: "lo", native: "ລາວ" },
  { code: "la", native: "Latina" },
  { code: "lv", native: "Latviešu" },
  { code: "ln", native: "Lingála" },
  { code: "lt", native: "Lietuvių" },
  { code: "lg", native: "Luganda" },
  { code: "lb", native: "Lëtzebuergesch" },
  { code: "mk", native: "Македонски" },
  { code: "mai", native: "मैथिली" },
  { code: "mg", native: "Malagasy" },
  { code: "ms", native: "Bahasa Melayu" },
  { code: "ml", native: "മലയാളം" },
  { code: "mt", native: "Malti" },
  { code: "mi", native: "Te Reo Māori" },
  { code: "mr", native: "मराठी" },
  { code: "mni-Mtei", native: "ꯃꯤꯇꯩꯂꯣꯟ" },
  { code: "lus", native: "Mizo ṭawng" },
  { code: "mn", native: "Монгол" },
  { code: "my", native: "မြန်မာ" },
  { code: "ne", native: "नेपाली" },
  { code: "no", native: "Norsk" },
  { code: "or", native: "ଓଡ଼ିଆ" },
  { code: "om", native: "Afaan Oromoo" },
  { code: "ps", native: "پښتو" },
  { code: "fa", native: "فارسی" },
  { code: "pl", native: "Polski" },
  { code: "pt", native: "Português" },
  { code: "pa", native: "ਪੰਜਾਬੀ" },
  { code: "qu", native: "Runasimi" },
  { code: "ro", native: "Română" },
  { code: "ru", native: "Русский" },
  { code: "sm", native: "Gagana Samoa" },
  { code: "sa", native: "संस्कृतम्" },
  { code: "gd", native: "Gàidhlig" },
  { code: "nso", native: "Sepedi" },
  { code: "sr", native: "Српски" },
  { code: "st", native: "Sesotho" },
  { code: "sn", native: "ChiShona" },
  { code: "sd", native: "سنڌي" },
  { code: "si", native: "සිංහල" },
  { code: "sk", native: "Slovenčina" },
  { code: "sl", native: "Slovenščina" },
  { code: "so", native: "Soomaali" },
  { code: "es", native: "Español" },
  { code: "su", native: "Basa Sunda" },
  { code: "sw", native: "Kiswahili" },
  { code: "sv", native: "Svenska" },
  { code: "tg", native: "Тоҷикӣ" },
  { code: "ta", native: "தமிழ்" },
  { code: "tt", native: "Татар теле" },
  { code: "te", native: "తెలుగు" },
  { code: "th", native: "ไทย" },
  { code: "ti", native: "ትግርኛ" },
  { code: "ts", native: "Xitsonga" },
  { code: "tr", native: "Türkçe" },
  { code: "tk", native: "Türkmençe" },
  { code: "ak", native: "Twi" },
  { code: "uk", native: "Українська" },
  { code: "ur", native: "اردو" },
  { code: "ug", native: "ئۇيغۇرچە" },
  { code: "uz", native: "Oʻzbekcha" },
  { code: "vi", native: "Tiếng Việt" },
  { code: "cy", native: "Cymraeg" },
  { code: "xh", native: "isiXhosa" },
  { code: "yi", native: "ייִדיש" },
  { code: "yo", native: "Yorùbá" },
  { code: "zu", native: "isiZulu" }
];

/**
 * Render the full language list into the dropdown <ul>.
 * Each <li> keeps a data-lang-code attribute used by script.js to drive
 * the existing (unmodified) Google Translate widget.
 * @param {HTMLElement} listEl
 */
function ziabridgePopulateLanguageList(listEl) {
  if (!listEl) return;
  listEl.innerHTML = "";
  ZIABRIDGE_LANGUAGES.forEach(function (lang) {
    const li = document.createElement("li");
    li.setAttribute("data-lang-code", lang.code);
    li.textContent = lang.native;
    listEl.appendChild(li);
  });
}
